name = "UPPE"
uuid = "45f285ff-ff9d-451c-aa08-ec013b3cde69"
authors = ["iamfedoroff <iamfedoroff@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
